/**
 * routes/sitemap.js
 * ────────────────────────────────────────────────────────────────
 * Generates a dynamic XML sitemap for incotechsolutions.com.
 *
 * Priority tiers:
 *   1.0  →  Homepage          /
 *   0.9  →  SEO city pages    /repair/:city  (from seo_entities)
 *   0.8  →  Catalog           /catalog
 *   0.7  →  Product pages     /product/:slug (in_stock only, from products)
 *
 * robots.txt is also handled here.
 * ────────────────────────────────────────────────────────────────
 */

const express = require('express');
const router  = express.Router();
const pool    = require('../config/db');

const BASE_URL    = 'https://incotechsolutions.com';
const CACHE_TTL   = 60 * 60 * 1000; // 1 hour

// ── In-memory cache for the generated XML ────────────────────────
let sitemapCache = null;
let cacheExpiry  = 0;

// ── Helpers ──────────────────────────────────────────────────────
function toW3CDate(date) {
  return new Date(date).toISOString().split('T')[0]; // YYYY-MM-DD
}

function urlEntry(loc, lastmod, changefreq, priority) {
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

// ── Sitemap Generator ─────────────────────────────────────────────
async function buildSitemap() {
  const today = toW3CDate(new Date());

  // 1. Static pages
  const staticPages = [
    urlEntry(`${BASE_URL}/`,        today, 'daily',   '1.0'),
    urlEntry(`${BASE_URL}/catalog`, today, 'daily',   '0.8'),
  ];

  // 2. SEO city corridor pages
  const [cities] = await pool.query(
    'SELECT city_slug, updated_at FROM seo_entities ORDER BY id ASC',
  );
  const cityPages = cities.map((c) =>
    urlEntry(
      `${BASE_URL}/repair/${c.city_slug}`,
      toW3CDate(c.updated_at || new Date()),
      'weekly',
      '0.9',
    ),
  );

  // 3. In-stock product pages (best for SEO — sold items excluded)
  const [products] = await pool.query(
    "SELECT slug, updated_at FROM products WHERE status = 'in_stock' ORDER BY id ASC",
  );
  const productPages = products.map((p) =>
    urlEntry(
      `${BASE_URL}/product/${p.slug}`,
      toW3CDate(p.updated_at || new Date()),
      'weekly',
      '0.7',
    ),
  );

  const allEntries = [...staticPages, ...cityPages, ...productPages];

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${allEntries.join('\n')}
</urlset>`;
}

// ── GET /sitemap.xml ──────────────────────────────────────────────
router.get('/sitemap.xml', async (_req, res) => {
  try {
    // Serve cached version if still fresh
    if (sitemapCache && Date.now() < cacheExpiry) {
      res.header('Content-Type', 'application/xml; charset=utf-8');
      res.header('X-Sitemap-Cache', 'HIT');
      return res.send(sitemapCache);
    }

    const xml = await buildSitemap();
    sitemapCache = xml;
    cacheExpiry  = Date.now() + CACHE_TTL;

    res.header('Content-Type', 'application/xml; charset=utf-8');
    res.header('X-Sitemap-Cache', 'MISS');
    return res.send(xml);

  } catch (error) {
    console.error('[Sitemap] generation error:', error);
    return res.status(500).send('Failed to generate sitemap.');
  }
});

// ── GET /robots.txt ───────────────────────────────────────────────
router.get('/robots.txt', (_req, res) => {
  const robots = `# robots.txt — incotechsolutions.com
# Generated by Inco Tech Solutions SEO Engine

User-agent: *
Allow: /
Allow: /repair/
Allow: /catalog
Allow: /product/

# Allow public APIs — Googlebot needs these to render product/city pages via JavaScript
Allow: /api/products
Allow: /api/categories
Allow: /api/seo

# Block sensitive/admin endpoints from crawlers
Disallow: /admin/
Disallow: /api/auth/
Disallow: /api/repairs/
Disallow: /api/dashboard/
Disallow: /api/settings/

# Block search/filter query params from being indexed as duplicate pages
Disallow: /catalog?*

# Canonical sitemap location
Sitemap: ${BASE_URL}/sitemap.xml

# Crawl delay (be polite to Googlebot)
Crawl-delay: 1
`;

  res.header('Content-Type', 'text/plain; charset=utf-8');
  res.send(robots);
});

// ── Cache invalidation helper (call after DB updates) ─────────────
function invalidateSitemapCache() {
  sitemapCache = null;
  cacheExpiry  = 0;
}

module.exports = router;
module.exports.invalidateSitemapCache = invalidateSitemapCache;
